---
- hosts: localhost
  vars:
    git_base: https://github.com
    public_ip: 192.168.27.100
    version: master
    cirros_arch: x86_64
    neutron: True
    swift: True
    security_groups: False
    tempest: False
    trove: False
    designate: False
    ceilometer: False
    designate_agent: False
    designate_sink: False
    neutron_lbaas: False
    neutron_vpn: False
    neutron_fwaas: False
    ceph: False
    keyring_config_dir: /home/vagrant/.local/share/python_keyring

  tasks:
    - name: create keyring config directory
      file: >
        state=directory
        dest={{ keyring_config_dir }}

    - name: copy keyring config file to workaround https://bugs.launchpad.net/bugs/1242992
      copy: >
        src=files/keyringrc.cfg
        dest={{ keyring_config_dir }}/keyringrc.cfg

    - name: install git
      apt: "name=git update_cache=yes"
      sudo: True
      
    - name: git config https instead git
      command: git config --global url."https://".insteadOf git://
      sudo: True

    - name: checkout devstack
      git: "repo={{ git_base }}/openstack-dev/devstack.git dest=/home/vagrant/devstack version={{ version }}"

    - name: checkout designate
      git: "repo={{ git_base }}/openstack/designate.git dest=/home/vagrant/designate version={{ version }}"
      when: designate

    - name: install designate extension
      command: bash -c 'cd /home/vagrant/devstack; /home/vagrant/designate/contrib/devstack/install.sh'
      when: designate

    - name: local.conf
      template: src=templates/local.conf.j2 dest=/home/vagrant/devstack/local.conf

    - name: source openrc in profile
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'

    - name: enable eth2
      command: ip link set dev eth2 up
      sudo: True

